#! /bin/bash

N=13
bindir=.

while getopts ":n:b:a" opt; do
    case $opt in
        n) N=$OPTARG;;
        b) bindir=$(OPTARG);;
        a) bindir=bin/n$N;;
    esac
done

root="$(dirname "$0")"
mkdir -p $bindir
D=$((2**N))

for f in $root/*".in"
do
    sed "\
        s:@root@:$root:;\
        s:@bindir@:$bindir:;\
        s:@N@:$N:;\
        s:@D@:$D:;\
        " < "$f" > "$(basename "${f%.in}")"
done

absroot=$(cd "$root"; pwd)

makelink() {
    if [ ! -e "$bindir"/$1 ]; then
        ln -s "$absroot"/$1 "$bindir"/$1
    fi
}

makelink graphs
makelink output
