#! /bin/bash

version=$(git describe --abbrev=0)

N=13
bindir=.
autodir=0

while getopts ":n:b:a" opt; do
    case $opt in
        n) N=$OPTARG;;
        b) bindir=$(OPTARG);;
        a) autodir=1;;
    esac
done

if [ $autodir -eq 1 ]; then bindir=build/bin/n$N; fi
root="$(dirname "$0")"
mkdir -p $bindir
D=$((2**N))

for f in $root/*".in"
do
    sed "\
        s:@root@:$root:;\
        s:@bindir@:$bindir:;\
        s:@version@:$version:;\
        s:@N@:$N:;\
        s:@D@:$D:;\
        " < "$f" > "$(basename "${f%.in}")"
done

absroot=$(cd "$root"; pwd)

makelink() {
    if [ ! -e "$bindir"/$1 ]; then
        ln -s "$absroot"/$1 "$bindir"/$1
    fi
}

makelink graphs
makelink output
