# Template parameters file

N:  13

# G_13 and G_13^' from the paper by Vinci et al.
graphs: [
    '98401a4024000c14400',
    '000010102c1c0068c21'
]

range:
    s:      [ 0.02, 1.00, 0.02]
    log_h:  [-2.00, 1.03, 0.03]

dh: 0.001

cg:
    eps: 1.0e-12
    itermax: 300

output_file: 'out.h5'
